/** Browser-side Dami speech. Sahara female African voice is primary. */
export interface SpeechHandle{stop():void;ended:Promise<void>;}type VoiceOptions={accent:string;gender:string;language:string};let sharedAudioContext:AudioContext|null=null;
export async function prepareAudioPlayback(){if(typeof window==="undefined")return;const AudioCtx=window.AudioContext??(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioCtx)return;sharedAudioContext??=new AudioCtx();if(sharedAudioContext.state==="suspended")await sharedAudioContext.resume();const source=sharedAudioContext.createBufferSource();source.buffer=sharedAudioContext.createBuffer(1,1,sharedAudioContext.sampleRate);source.connect(sharedAudioContext.destination);source.start(0);}
function cleanSpeechText(text:string){return text.replace(/\[(?:S\d+)\]/g,"").replace(/(^|\n)#{1,6}\s+/g,"$1").replace(/\*\*|__|`/g,"").replace(/^\s*[-*+]\s+/gm,"").replace(/\|/g,", ").replace(/\s*[:;]\s*/g,", ").replace(/\s{2,}/g," ").replace(/\s+([,.!?])/g,"$1").trim();}
function normaliseVoice(o:VoiceOptions):VoiceOptions{if(o.language==="sw")return{language:"sw",accent:"swahili",gender:"female"};if(o.language==="yo")return{language:"yo",accent:"yoruba",gender:"female"};if(o.language==="pcm")return{language:"pcm",accent:"pidgin",gender:"female"};return{language:"en",accent:o.accent||"yoruba",gender:"female"};}
function sentenceChunks(text:string){const clean=cleanSpeechText(text);const sentences=clean.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(s=>s.trim()).filter(Boolean)??[clean];const chunks:string[]=[];let current="";for(const sentence of sentences){const next=(current+" "+sentence).trim();if(next.length<=135)current=next;else{if(current)chunks.push(current);current=sentence;}}if(current)chunks.push(current);return chunks.filter(Boolean);}
async function playBlob(blob:Blob,isStopped:()=>boolean){if(isStopped())return;await prepareAudioPlayback();if(sharedAudioContext){const data=await blob.arrayBuffer(),decoded=await sharedAudioContext.decodeAudioData(data.slice(0));if(isStopped())return;await new Promise<void>(resolve=>{const source=sharedAudioContext!.createBufferSource();source.buffer=decoded;source.connect(sharedAudioContext!.destination);source.addEventListener("ended",()=>resolve(),{once:true});source.start();});return;}const url=URL.createObjectURL(blob);try{const audio=new Audio(url);audio.preload="auto";await audio.play();await new Promise<void>((resolve,reject)=>{audio.addEventListener("ended",()=>resolve(),{once:true});audio.addEventListener("error",()=>reject(new Error("Audio playback failed.")),{once:true});});}finally{URL.revokeObjectURL(url);}}
function browserSpeech(text:string,o:VoiceOptions):SpeechHandle{if(typeof window==="undefined"||!("speechSynthesis" in window))throw new Error("Dami couldn't play voice on this browser.");window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(cleanSpeechText(text));u.lang=o.language==="en"?"en-NG":o.language;u.rate=1.12;u.pitch=1.03;const voices=window.speechSynthesis.getVoices(),preferred=voices.find(v=>/female|woman|aria|jenny|zira/i.test(v.name)&&/en|nigeria|yoruba|africa/i.test(`${v.name} ${v.lang}`))??voices.find(v=>!/male/i.test(v.name)&&v.lang.toLowerCase().startsWith("en"));if(preferred)u.voice=preferred;let settle!:()=>void;const ended=new Promise<void>(r=>settle=r);u.addEventListener("end",settle,{once:true});u.addEventListener("error",settle,{once:true});window.speechSynthesis.speak(u);return{stop(){window.speechSynthesis.cancel();settle();},ended};}
async function requestChunk(text:string,o:VoiceOptions){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4500);try{let response=await fetch("/api/sahara-tts",{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({text,...o,gender:"female"})});if((response.status===404||response.status===405)&&!controller.signal.aborted)response=await fetch("/api/sahara/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,...o,gender:"female"})});if(!response.ok)return null;const blob=await response.blob();return blob.size?blob:null;}catch{return null;}finally{clearTimeout(timer);}}
async function saharaSpeech(text:string,o:VoiceOptions):Promise<SpeechHandle|null>{const chunks=sentenceChunks(text);if(!chunks.length)return null;let stopped=false,resolve!:()=>void;const ended=new Promise<void>(r=>resolve=r);void(async()=>{try{let next=requestChunk(chunks[0]!,o);for(let i=0;i<chunks.length&&!stopped;i++){const blob=await next;if(!blob)throw new Error("Sahara voice unavailable");next=i+1<chunks.length?requestChunk(chunks[i+1]!,o):Promise.resolve(null);await playBlob(blob,()=>stopped);}}catch{if(!stopped){const fallback=browserSpeech(chunks.join(" "),o);await fallback.ended;}}finally{resolve();}})();return{stop(){stopped=true;resolve();},ended};}
export async function speak(text:string,requested:VoiceOptions):Promise<SpeechHandle>{const o=normaliseVoice(requested);await prepareAudioPlayback().catch(()=>undefined);const handle=await saharaSpeech(cleanSpeechText(text),o).catch(()=>null);return handle??browserSpeech(text,o);}
