import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { DamiAvatar } from "@/components/DamiAvatar";
import { useVoiceSession } from "@/hooks/useVoiceSession";
import { storage } from "@/lib/storage";

export const Route=createFileRoute("/companion")({component:Companion});
type RecognitionEvent={results:ArrayLike<{0:{transcript:string}}>};type Recognition={continuous:boolean;interimResults:boolean;lang:string;start():void;stop():void;abort():void;onresult:((e:RecognitionEvent)=>void)|null;onend:(()=>void)|null;onerror:(()=>void)|null};type RecognitionCtor=new()=>Recognition;
type WakeStatus="starting"|"ready"|"error"|"unsupported"|"disabled"|"stopped"|"listening-local";
type DesktopBridge={isDesktop?:boolean;onWakeWord?:(cb:()=>void)=>void|(()=>void);getWakeStatus?:()=>Promise<WakeStatus>;onWakeStatus?:(cb:(s:WakeStatus)=>void)=>void|(()=>void);localTranscribe?:()=>Promise<string>;localSpeak?:(text:string)=>Promise<boolean>;stopLocalSpeech?:()=>Promise<boolean>};
function Companion(){
 const{readAloud,startListening,ask,robotState,level,stage,statusText}=useVoiceSession();const recognitionRef=useRef<Recognition|null>(null),stageRef=useRef(stage),activatingRef=useRef(false);const[wakeAvailable,setWakeAvailable]=useState(true),[wakeActive,setWakeActive]=useState(false),[nativeWakeStatus,setNativeWakeStatus]=useState<WakeStatus>("starting");useEffect(()=>{stageRef.current=stage;},[stage]);
 const activate=useCallback(async()=>{if(activatingRef.current||!["idle","answered","error"].includes(stageRef.current))return;activatingRef.current=true;recognitionRef.current?.stop();const bridge=(window as typeof window&{damiDesktop?:DesktopBridge}).damiDesktop;
  try{
   if(bridge?.isDesktop&&bridge.localTranscribe){
    // Desktop activation is completely independent of Sahara: local greeting + local STT.
    if(bridge.localSpeak){try{await bridge.localSpeak("How can I help you today?");}catch{void readAloud("How can I help you today?");}}else void readAloud("How can I help you today?");
    try{const text=await bridge.localTranscribe();if(text?.trim())await ask(text.trim());else throw new Error("I didn't hear a clear question.");}
    catch(err){console.warn("Local desktop speech fallback unavailable",err);await startListening();}
   }else{
    void readAloud("How can I help you today?");
    await startListening();
   }
  }finally{activatingRef.current=false;}
 },[ask,readAloud,startListening]);
 useEffect(()=>{const bridge=(window as typeof window&{damiDesktop?:DesktopBridge}).damiDesktop;if(!bridge?.isDesktop)return;if(!storage.getSettings().wakeWordEnabled){setWakeAvailable(false);setWakeActive(false);setNativeWakeStatus("disabled");return;}let wc:void|(()=>void),sc:void|(()=>void),cancelled=false;setWakeAvailable(true);if(bridge.onWakeWord)wc=bridge.onWakeWord(()=>void activate());if(bridge.onWakeStatus)sc=bridge.onWakeStatus(s=>{setNativeWakeStatus(s);setWakeActive(s==="ready");setWakeAvailable(!["error","unsupported","stopped"].includes(s));});if(bridge.getWakeStatus)void bridge.getWakeStatus().then(s=>{if(cancelled)return;setNativeWakeStatus(s);setWakeActive(s==="ready");setWakeAvailable(!["error","unsupported","stopped"].includes(s));}).catch(()=>{if(!cancelled){setNativeWakeStatus("error");setWakeActive(false);setWakeAvailable(false);}});return()=>{cancelled=true;if(typeof wc==="function")wc();if(typeof sc==="function")sc();};},[activate]);
 useEffect(()=>{const bridge=(window as typeof window&{damiDesktop?:DesktopBridge}).damiDesktop;if(bridge?.isDesktop)return;const settings=storage.getSettings();if(!settings.wakeWordEnabled){setWakeActive(false);return;}const sw=window as typeof window&{SpeechRecognition?:RecognitionCtor;webkitSpeechRecognition?:RecognitionCtor};const Ctor=sw.SpeechRecognition??sw.webkitSpeechRecognition;if(!Ctor){setWakeAvailable(false);return;}const r=new Ctor();r.continuous=true;r.interimResults=true;r.lang="en-US";r.onresult=e=>{const latest=e.results[e.results.length-1]?.[0]?.transcript?.toLowerCase()??"";if(/hey (dami|dummy|demi)/.test(latest))void activate();};r.onerror=()=>setWakeActive(false);r.onend=()=>{setWakeActive(false);if(!["idle","answered","error"].includes(stageRef.current)||!storage.getSettings().wakeWordEnabled)return;window.setTimeout(()=>{if(recognitionRef.current!==r)return;try{r.start();setWakeActive(true);}catch{setWakeActive(false);}},700);};recognitionRef.current=r;try{r.start();setWakeActive(true);}catch{setWakeActive(false);}return()=>{r.onend=null;r.abort();if(recognitionRef.current===r)recognitionRef.current=null;};},[activate]);
 const bridge=(window as typeof window&{damiDesktop?:DesktopBridge}).damiDesktop;const isDesktop=Boolean(bridge?.isDesktop);const desktopIdleText=nativeWakeStatus==="starting"?"Starting Hey Dami…":nativeWakeStatus==="listening-local"?"I'm listening — ask your question":nativeWakeStatus==="ready"?'Say "Hey Dami"':nativeWakeStatus==="disabled"?"Wake word is off — double-click Dami":"Hey Dami unavailable — double-click Dami";const idleText=isDesktop?desktopIdleText:wakeAvailable?(wakeActive?'Say "Hey Dami"':"Wake listener unavailable — tap Dami"):"Tap Dami to talk";
 if(isDesktop)return <main className="flex h-screen w-screen select-none items-center justify-center overflow-hidden bg-transparent p-0"><button type="button" onDoubleClick={()=>void activate()} className="grid h-[180px] w-[180px] place-items-center overflow-hidden rounded-full bg-transparent p-0 outline-none transition-transform hover:scale-[1.02] focus-visible:ring-2 focus-visible:ring-primary" aria-label="Talk with Dami"><DamiAvatar state={robotState} level={level} size={180} className="overflow-hidden rounded-full"/></button></main>;
 return <main className="flex min-h-screen select-none flex-col items-center justify-end bg-transparent p-2 text-center"><button type="button" onDoubleClick={()=>void activate()} onClick={()=>void activate()} className="rounded-full bg-transparent p-0 outline-none transition-transform hover:scale-[1.02] focus-visible:ring-2 focus-visible:ring-primary" aria-label="Talk with Dami"><DamiAvatar state={robotState} level={level} size={205}/></button><div className="-mt-2 rounded-full border border-border/70 bg-background/90 px-4 py-2 shadow-lg backdrop-blur"><p className="text-sm font-semibold">Dami</p><p className="max-w-[230px] truncate text-[11px] text-muted-foreground">{stage==="idle"?idleText:statusText}</p></div></main>;
}
