/** Dami voice session state machine. */
import { useServerFn } from "@tanstack/react-start";
import { useCallback, useEffect, useRef, useState } from "react";
import { askDami } from "@/lib/dami.functions";
import { getDamiLanguage } from "@/lib/languages";
import { newId, storage } from "@/lib/storage";
import { speak, startRecording, transcribeSamples, type Recorder, type SpeechHandle } from "@/services/sahara/browser";
import type { DamiState, ResearchAnswer, ResearchSession, VoiceStage } from "@/lib/types";

const STAGE_TO_ROBOT: Record<VoiceStage,DamiState>={welcome:"welcome",idle:"idle","requesting-permission":"idle",listening:"listening",transcribing:"thinking",researching:"thinking",answered:"success",speaking:"speaking",error:"error"};
export const STAGE_LABEL:Record<VoiceStage,string>={welcome:"Hi, I'm Dami. Talk to me when you're ready.",idle:"Ready when you are.","requesting-permission":"Waiting for microphone permission...",listening:"I'm listening. Just speak naturally and I'll know when you're done.",transcribing:"Finishing your transcript...",researching:"I'm checking the law and the strongest available authorities...",answered:"I found something useful for you.",speaking:"I'm speaking...",error:"Something went wrong."};
const END_OF_SPEECH_SILENCE_MS=1000,LISTENING_GRACE_MS=400,SPEECH_CONFIRM_MS=120,MIN_SPEECH_THRESHOLD=.032,NOISE_MULTIPLIER=2,NOISE_MARGIN=.016;

export function useVoiceSession(){
 const[stage,setStage]=useState<VoiceStage>("welcome"),[question,setQuestion]=useState(""),[partial,setPartial]=useState(""),[answer,setAnswer]=useState<ResearchAnswer|null>(null),[error,setError]=useState<string|null>(null),[level,setLevel]=useState(0),[session,setSession]=useState<ResearchSession|null>(null),[speechPaused,setSpeechPaused]=useState(false);
 const recorderRef=useRef<Recorder|null>(null),speechRef=useRef<SpeechHandle|null>(null),levelTimer=useRef<ReturnType<typeof setInterval>|null>(null),cancelled=useRef(false),autoStoppingRef=useRef(false);const runResearch=useServerFn(askDami);
 const stopLevelMeter=useCallback(()=>{if(levelTimer.current)clearInterval(levelTimer.current);levelTimer.current=null;setLevel(0);},[]);
 useEffect(()=>{const t=setTimeout(()=>setStage(c=>c==="welcome"?"idle":c),1200);return()=>clearTimeout(t);},[]);
 useEffect(()=>()=>{recorderRef.current?.cancel();speechRef.current?.stop();if(levelTimer.current)clearInterval(levelTimer.current);},[]);
 const clear=useCallback(()=>{cancelled.current=true;autoStoppingRef.current=false;recorderRef.current?.cancel();recorderRef.current=null;speechRef.current?.stop();speechRef.current=null;setSpeechPaused(false);stopLevelMeter();setStage("idle");setQuestion("");setPartial("");setAnswer(null);setError(null);setSession(null);},[stopLevelMeter]);
 const stopSpeaking=useCallback(()=>{speechRef.current?.stop();speechRef.current=null;setSpeechPaused(false);setStage(c=>c==="speaking"?"answered":c);},[]);
 const toggleSpeechPause=useCallback(()=>{const handle=speechRef.current;if(!handle)return;if(handle.isPaused()){handle.resume();setSpeechPaused(false);}else{handle.pause();setSpeechPaused(true);}},[]);
 const readAloud=useCallback(async(text:string,onStarted?:()=>void)=>{const settings=storage.getSettings(),language=getDamiLanguage(settings.speechLanguage);speechRef.current?.stop();setSpeechPaused(false);try{setStage("speaking");const handle=await speak(text,{accent:settings.voiceAccent||language.preferredAccent,gender:settings.voiceGender,language:language.ttsLanguage});speechRef.current=handle;await handle.started;if(speechRef.current!==handle)return;onStarted?.();await handle.ended;if(speechRef.current===handle)speechRef.current=null;setSpeechPaused(false);setStage("answered");}catch(err){onStarted?.();speechRef.current=null;setSpeechPaused(false);setStage("answered");setError(err instanceof Error?err.message:"I couldn't read that answer aloud.");}},[]);
 const ask=useCallback(async(text:string)=>{const trimmed=text.trim();if(trimmed.length<3){setError("Give me a little more to work with.");setStage("error");return;}cancelled.current=false;setQuestion(trimmed);setPartial("");setError(null);setAnswer(null);setStage("researching");try{const result=await runResearch({data:{question:trimmed}});if(cancelled.current)return;const record:ResearchSession={id:newId("ses"),conversationId:null,question:trimmed,answer:result,createdAt:new Date().toISOString(),saved:false};storage.saveSession(record);setSession(record);if(storage.getSettings().speakAnswers){void readAloud(result.answer,()=>setAnswer(result));}else{setAnswer(result);setStage("answered");}}catch(err){if(cancelled.current)return;console.error(err);setError(err instanceof Error&&err.message?err.message:"I couldn't complete that research. Please try again.");setStage("error");}},[readAloud,runResearch]);
 const processRecording=useCallback(async(recorder:Recorder)=>{stopLevelMeter();const browserTranscript=recorder.transcript().trim();if(browserTranscript)setPartial(browserTranscript);setStage("transcribing");const settings=storage.getSettings(),language=getDamiLanguage(settings.speechLanguage);try{const samples=await recorder.stop();const result=await transcribeSamples(samples,{language:language.code,codeSwitching:language.codeSwitched,browserTranscript});if(cancelled.current)return;setPartial("");setQuestion(result.text);await ask(result.text);}catch(err){if(cancelled.current)return;console.error(err);setError(err instanceof Error&&err.message?err.message:"I couldn't turn that recording into text.");setStage("error");}finally{autoStoppingRef.current=false;}},[ask,stopLevelMeter]);
 const startListening=useCallback(async()=>{cancelled.current=false;autoStoppingRef.current=false;setError(null);setAnswer(null);setPartial("");setQuestion("");setStage("requesting-permission");const settings=storage.getSettings(),language=getDamiLanguage(settings.speechLanguage);try{const recognitionLang=language.code==="en"?"en-NG":language.code;const recorder=await startRecording(settings.maxRecordingSeconds,recognitionLang);recorderRef.current=recorder;setStage("listening");const startedAt=Date.now();let noiseFloor=.01,speechDetected=false,speechStartedAt:number|null=null,silenceStartedAt:number|null=null;levelTimer.current=setInterval(()=>{const currentRecorder=recorderRef.current;if(!currentRecorder||autoStoppingRef.current)return;const now=Date.now(),currentLevel=currentRecorder.level();setLevel(currentLevel);const live=currentRecorder.transcript();if(live)setPartial(live);if(now-startedAt<LISTENING_GRACE_MS){noiseFloor=Math.min(.035,noiseFloor*.8+currentLevel*.2);if(currentLevel>=.08)speechDetected=true;return;}const speechThreshold=Math.max(MIN_SPEECH_THRESHOLD,Math.min(.12,noiseFloor*NOISE_MULTIPLIER+NOISE_MARGIN)),quietThreshold=Math.max(MIN_SPEECH_THRESHOLD*.8,speechThreshold*.72);if(currentLevel>=speechThreshold){if(speechStartedAt===null)speechStartedAt=now;if(now-speechStartedAt>=SPEECH_CONFIRM_MS)speechDetected=true;silenceStartedAt=null;return;}speechStartedAt=null;if(!speechDetected){noiseFloor=Math.min(.035,noiseFloor*.96+currentLevel*.04);return;}if(currentLevel<=quietThreshold){if(silenceStartedAt===null)silenceStartedAt=now;if(now-silenceStartedAt>=END_OF_SPEECH_SILENCE_MS){autoStoppingRef.current=true;recorderRef.current=null;void processRecording(currentRecorder);}}else silenceStartedAt=null;},70);}catch(err){recorderRef.current=null;stopLevelMeter();setError(err instanceof Error&&err.name==="MicrophoneError"?err.message:"I couldn't start listening. You can type your question instead.");setStage("error");}},[processRecording,stopLevelMeter]);
 const stopListening=useCallback(async()=>{const recorder=recorderRef.current;if(!recorder||autoStoppingRef.current)return;autoStoppingRef.current=true;recorderRef.current=null;await processRecording(recorder);},[processRecording]);
 const cancelListening=useCallback(()=>{cancelled.current=true;autoStoppingRef.current=false;recorderRef.current?.cancel();recorderRef.current=null;stopLevelMeter();setPartial("");setStage("idle");},[stopLevelMeter]);
 const retry=useCallback(()=>{setError(null);if(question)void ask(question);else setStage("idle");},[ask,question]);
 return{stage,robotState:STAGE_TO_ROBOT[stage]as DamiState,statusText:error&&stage==="error"?error:STAGE_LABEL[stage],question,partial,answer,error,level,session,speechPaused,isBusy:stage==="transcribing"||stage==="researching",startListening,stopListening,cancelListening,ask,retry,clear,readAloud,stopSpeaking,toggleSpeechPause,setQuestion};
}
