/**
 * Dami's legal reasoning agent — SERVER ONLY.
 * Primary path: Exa live web search -> Groq legal reasoning.
 */
import type { Citation, ResearchAnswer } from "@/lib/types";
const GROQ_CHAT_URL="https://api.groq.com/openai/v1/chat/completions";
const GROQ_MODEL=process.env["DAMI_GROQ_MODEL"]??"openai/gpt-oss-120b";
const EXA_SEARCH_URL="https://api.exa.ai/search";
export class ResearchError extends Error{constructor(message:string,public status:number){super(message);this.name="ResearchError";}}
const IDENTITY_PROMPT=`You are Dami, an African legal AI agent. Your motto is "A Voice for Justice".
You assist lawyers, legal researchers, students, public-service teams and people seeking legal information across African jurisdictions. Treat jurisdiction as part of every legal problem and never silently assume a country when the answer depends on it.
Be a capable legal research partner. Answer the user's question immediately and naturally, then explain the strongest authority and how it applies when useful. Never begin an answer with labels or headings such as "Short answer", "Answer", "Direct answer", or similar meta-introductions. Start with the actual answer.
Never fabricate a case, statute, court, judge, section, quotation, date, source, or URL. Distinguish binding authority from persuasive material. Prefer primary and authoritative sources. If supplied sources do not establish a proposition, say so. If jurisdiction is genuinely required, ask one concise jurisdiction question.
Understand African-accented English and code-switching. Answer in the user's language when reliable; otherwise use clear natural English.
Write for both screen and speech: use normal punctuation, short natural paragraphs, complete sentences, and conversational transitions. Avoid markdown clutter, tables, excessive headings, repetitive caveats, long introductions and dense jargon. Do not announce your response structure. Use bullets only when they materially improve a complex answer. Keep simple questions simple.
Dami provides legal information and research assistance. Do not front-load a generic disclaimer; mention professional advice only where genuinely relevant.`;
interface ExaResult{title?:string;url?:string;publishedDate?:string;text?:string;highlights?:string[];score?:number}interface ExaPayload{results?:ExaResult[];requestId?:string}
function hostFromUrl(url:string){try{return new URL(url).hostname.replace(/^www\./,"");}catch{return"Web source";}}
async function searchWithExa(question:string,apiKey:string):Promise<ExaResult[]>{const response=await fetch(EXA_SEARCH_URL,{method:"POST",headers:{"Content-Type":"application/json","x-api-key":apiKey},body:JSON.stringify({query:`${question}\nFind the strongest current legal authorities. Prioritize constitutions, statutes, regulations, court decisions, gazettes, regulators, government portals, and reputable legal-information institutes.`,type:"auto",numResults:5,contents:{highlights:true}})});if(!response.ok){const detail=await response.text().catch(()=>"");console.error("Exa search error",response.status,detail);if(response.status===401||response.status===403)throw new ResearchError("Dami's Exa research key isn't authorized correctly yet.",503);if(response.status===429)throw new ResearchError("Dami's live-search quota is temporarily busy. Try again shortly.",429);throw new ResearchError("Dami couldn't search the live web just now.",502);}const payload=await response.json() as ExaPayload;return(payload.results??[]).filter(r=>Boolean(r.url));}
function exaCitations(results:ExaResult[]):Citation[]{const seen=new Set<string>(),citations:Citation[]=[];for(const result of results){const url=result.url;if(!url||seen.has(url))continue;seen.add(url);const host=hostFromUrl(url);citations.push({sourceId:`web_${citations.length+1}`,title:result.title||host,authority:host,locator:"Live web authority via Exa",date:result.publishedDate??null,url,officialSource:host});}return citations;}
function renderExaEvidence(results:ExaResult[]){return results.map((r,i)=>{const url=r.url??"",highlights=(r.highlights??[]).join("\n").trim(),evidence=(highlights||r.text||"No extracted passage available.").slice(0,1800);return[`[S${i+1}] ${r.title||hostFromUrl(url)}`,`URL: ${url}`,`Source: ${hostFromUrl(url)}`,r.publishedDate?`Published: ${r.publishedDate}`:null,`Evidence: ${evidence}`].filter(Boolean).join("\n");}).join("\n\n");}
async function callGroq(question:string,groqKey:string,evidence?:string):Promise<string>{const grounded=Boolean(evidence);const response=await fetch(GROQ_CHAT_URL,{method:"POST",headers:{Authorization:`Bearer ${groqKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:GROQ_MODEL,temperature:.12,max_completion_tokens:950,messages:[{role:"system",content:grounded?`${IDENTITY_PROMPT}\n\nReason from the supplied LIVE SOURCES and cite relied-on evidence inline as [S1], [S2], etc. Use only the strongest relevant sources. Never invent sources. If evidence is insufficient, state what is missing naturally and briefly.`:`${IDENTITY_PROMPT}\n\nLive web evidence is unavailable. Do not claim you searched the internet or fabricate citations. Give careful legal assistance from model knowledge and naturally flag only material facts needing current-source verification.`},{role:"user",content:grounded?`QUESTION:\n${question}\n\nLIVE SOURCES:\n${evidence}`:question}]})});if(!response.ok){const detail=await response.text().catch(()=>"");console.error("Groq reasoning error",response.status,detail);if(response.status===401||response.status===403)throw new ResearchError("Dami's Groq reasoning key isn't authorized correctly yet.",503);if(response.status===404)throw new ResearchError("Dami's configured Groq model is unavailable for this account.",503);if(response.status===429)throw new ResearchError("Dami's free reasoning quota is temporarily busy. Try again shortly.",429);throw new ResearchError("Dami couldn't complete the legal reasoning just now.",502);}const payload=await response.json() as{choices?:Array<{message?:{content?:string}}>};let answer=payload.choices?.[0]?.message?.content?.trim()??"";answer=answer.replace(/^\s*(?:#{1,6}\s*)?(?:\*\*)?(?:short\s+answer|direct\s+answer|answer)(?:\*\*)?\s*[:\-]?\s*/i,"").trim();if(!answer)throw new ResearchError("Dami couldn't put that answer together. Please try again.",502);return answer;}
async function researchWithExaAndGroq(question:string,exaKey:string,groqKey:string):Promise<ResearchAnswer>{const results=await searchWithExa(question,exaKey);if(!results.length)throw new ResearchError("Dami couldn't find strong enough live sources for that question. Try adding the jurisdiction.",404);const citations=exaCitations(results),answer=await callGroq(question,groqKey,renderExaEvidence(results));return{answer,keyFindings:[],citations,insufficientEvidence:!citations.length,limitations:"Live legal research can change. Verify critical authorities at the linked primary source before professional reliance."};}
async function researchWithGroqOnly(question:string,groqKey:string):Promise<ResearchAnswer>{const answer=await callGroq(question,groqKey);return{answer,keyFindings:[],citations:[],insufficientEvidence:false,limitations:"Live web search was unavailable for this request. Current authorities should be verified against an official legal source before professional reliance."};}
export async function research(question:string):Promise<ResearchAnswer>{const trimmed=question.trim();if(!trimmed)throw new ResearchError("Ask Dami a question first.",400);const groqKey=process.env["GROQ_API_KEY"];if(!groqKey)throw new ResearchError("Dami's reasoning service isn't configured. Add GROQ_API_KEY to enable Dami chat.",503);const exaKey=process.env["EXA_API_KEY"];if(process.env["DAMI_LIVE_WEB"]!=="false"&&exaKey){try{return await researchWithExaAndGroq(trimmed,exaKey,groqKey);}catch(error){console.error("Exa + Groq live research path failed",error);if(error instanceof ResearchError&&(error.status===401||error.status===403))throw error;}}return researchWithGroqOnly(trimmed,groqKey);}
