/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ApiSaharaSttRouteImport } from './routes/api/sahara.stt'
import { Route as ApiSaharaTtsRouteImport } from './routes/api/sahara.tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaharaSttRoute = ApiSaharaSttRouteImport.update({
  id: '/api/sahara/stt',
  path: '/api/sahara/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaharaTtsRoute = ApiSaharaTtsRouteImport.update({
  id: '/api/sahara/tts',
  path: '/api/sahara/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/research': typeof ResearchRoute
  '/sources': typeof SourcesRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/research': typeof ResearchRoute
  '/sources': typeof SourcesRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/research': typeof ResearchRoute
  '/sources': typeof SourcesRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/research'
    | '/sources'
    | '/api/sahara/stt'
    | '/api/sahara/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/research'
    | '/sources'
    | '/api/sahara/stt'
    | '/api/sahara/tts'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/research'
    | '/sources'
    | '/api/sahara/stt'
    | '/api/sahara/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ResearchRoute: typeof ResearchRoute
  SourcesRoute: typeof SourcesRoute
  ApiSaharaSttRoute: typeof ApiSaharaSttRoute
  ApiSaharaTtsRoute: typeof ApiSaharaTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sahara/stt': {
      id: '/api/sahara/stt'
      path: '/api/sahara/stt'
      fullPath: '/api/sahara/stt'
      preLoaderRoute: typeof ApiSaharaSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sahara/tts': {
      id: '/api/sahara/tts'
      path: '/api/sahara/tts'
      fullPath: '/api/sahara/tts'
      preLoaderRoute: typeof ApiSaharaTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ResearchRoute: ResearchRoute,
  SourcesRoute: SourcesRoute,
  ApiSaharaSttRoute: ApiSaharaSttRoute,
  ApiSaharaTtsRoute: ApiSaharaTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
