/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSaharaSttRouteImport } from './routes/api/sahara.stt'
import { Route as ApiSaharaTtsRouteImport } from './routes/api/sahara.tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaharaSttRoute = ApiSaharaSttRouteImport.update({
  id: '/api/sahara/stt',
  path: '/api/sahara/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaharaTtsRoute = ApiSaharaTtsRouteImport.update({
  id: '/api/sahara/tts',
  path: '/api/sahara/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/sahara/stt' | '/api/sahara/tts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/sahara/stt' | '/api/sahara/tts'
  id: '__root__' | '/' | '/api/sahara/stt' | '/api/sahara/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSaharaSttRoute: typeof ApiSaharaSttRoute
  ApiSaharaTtsRoute: typeof ApiSaharaTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sahara/stt': {
      id: '/api/sahara/stt'
      path: '/api/sahara/stt'
      fullPath: '/api/sahara/stt'
      preLoaderRoute: typeof ApiSaharaSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sahara/tts': {
      id: '/api/sahara/tts'
      path: '/api/sahara/tts'
      fullPath: '/api/sahara/tts'
      preLoaderRoute: typeof ApiSaharaTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSaharaSttRoute: ApiSaharaSttRoute,
  ApiSaharaTtsRoute: ApiSaharaTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
