/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VoiceSttRouteImport } from './routes/voice.stt'
import { Route as VoiceTtsRouteImport } from './routes/voice.tts'
import { Route as ApiSaharaSttRouteImport } from './routes/api/sahara.stt'
import { Route as ApiSaharaTtsRouteImport } from './routes/api/sahara.tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceSttRoute = VoiceSttRouteImport.update({
  id: '/voice/stt',
  path: '/voice/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceTtsRoute = VoiceTtsRouteImport.update({
  id: '/voice/tts',
  path: '/voice/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaharaSttRoute = ApiSaharaSttRouteImport.update({
  id: '/api/sahara/stt',
  path: '/api/sahara/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaharaTtsRoute = ApiSaharaTtsRouteImport.update({
  id: '/api/sahara/tts',
  path: '/api/sahara/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/companion': typeof CompanionRoute
  '/desktop': typeof DesktopRoute
  '/documents': typeof DocumentsRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/voice/stt': typeof VoiceSttRoute
  '/voice/tts': typeof VoiceTtsRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/companion': typeof CompanionRoute
  '/desktop': typeof DesktopRoute
  '/documents': typeof DocumentsRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/voice/stt': typeof VoiceSttRoute
  '/voice/tts': typeof VoiceTtsRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/companion': typeof CompanionRoute
  '/desktop': typeof DesktopRoute
  '/documents': typeof DocumentsRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/voice/stt': typeof VoiceSttRoute
  '/voice/tts': typeof VoiceTtsRoute
  '/api/sahara/stt': typeof ApiSaharaSttRoute
  '/api/sahara/tts': typeof ApiSaharaTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/companion'
    | '/desktop'
    | '/documents'
    | '/privacy'
    | '/research'
    | '/settings'
    | '/sources'
    | '/terms'
    | '/voice/stt'
    | '/voice/tts'
    | '/api/sahara/stt'
    | '/api/sahara/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/companion'
    | '/desktop'
    | '/documents'
    | '/privacy'
    | '/research'
    | '/settings'
    | '/sources'
    | '/terms'
    | '/voice/stt'
    | '/voice/tts'
    | '/api/sahara/stt'
    | '/api/sahara/tts'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/companion'
    | '/desktop'
    | '/documents'
    | '/privacy'
    | '/research'
    | '/settings'
    | '/sources'
    | '/terms'
    | '/voice/stt'
    | '/voice/tts'
    | '/api/sahara/stt'
    | '/api/sahara/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  CompanionRoute: typeof CompanionRoute
  DesktopRoute: typeof DesktopRoute
  DocumentsRoute: typeof DocumentsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  TermsRoute: typeof TermsRoute
  VoiceSttRoute: typeof VoiceSttRoute
  VoiceTtsRoute: typeof VoiceTtsRoute
  ApiSaharaSttRoute: typeof ApiSaharaSttRoute
  ApiSaharaTtsRoute: typeof ApiSaharaTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice/stt': {
      id: '/voice/stt'
      path: '/voice/stt'
      fullPath: '/voice/stt'
      preLoaderRoute: typeof VoiceSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice/tts': {
      id: '/voice/tts'
      path: '/voice/tts'
      fullPath: '/voice/tts'
      preLoaderRoute: typeof VoiceTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sahara/stt': {
      id: '/api/sahara/stt'
      path: '/api/sahara/stt'
      fullPath: '/api/sahara/stt'
      preLoaderRoute: typeof ApiSaharaSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sahara/tts': {
      id: '/api/sahara/tts'
      path: '/api/sahara/tts'
      fullPath: '/api/sahara/tts'
      preLoaderRoute: typeof ApiSaharaTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  CompanionRoute: CompanionRoute,
  DesktopRoute: DesktopRoute,
  DocumentsRoute: DocumentsRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  TermsRoute: TermsRoute,
  VoiceSttRoute: VoiceSttRoute,
  VoiceTtsRoute: VoiceTtsRoute,
  ApiSaharaSttRoute: ApiSaharaSttRoute,
  ApiSaharaTtsRoute: ApiSaharaTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
