type Body={text?:string;accent?:string;gender?:string;language?:string};
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8"}});}
function voice(body:Body){const language=body.language||"en";if(language==="sw")return{voice_language:"sw",voice_accent:"swahili",voice_gender:"female"};if(language==="yo")return{voice_language:"yo",voice_accent:"yoruba",voice_gender:"female"};if(language==="pcm")return{voice_language:"pcm",voice_accent:"pidgin",voice_gender:"female"};return{voice_language:"en",voice_accent:body.accent||"yoruba",voice_gender:"female"};}
export default async function handler(request:Request){
 if(request.method!=="POST")return json({error:"Method not allowed."},405);const key=process.env.INTRON_API_KEY;if(!key)return json({error:"Sahara voice is not configured."},503);
 let body:Body;try{body=await request.json() as Body;}catch{return json({error:"Invalid request body."},400);}const text=body.text?.trim();if(!text)return json({error:"There was nothing for Dami to read aloud."},400);
 const v=voice(body);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);
 try{const response=await fetch(process.env.SAHARA_TTS_GENERATE_URL??"https://infer.voice.intron.io/tts/v1/generate",{method:"POST",signal:controller.signal,headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({text:text.slice(0,1400),...v,output_audio_format:"wav"})});if(!response.ok){const detail=await response.text().catch(()=>"");return json({error:detail.slice(0,220)||`Sahara voice failed (HTTP ${response.status}).`},502);}const audio=await response.arrayBuffer();if(!audio.byteLength)return json({error:"Sahara returned no voice audio."},502);return new Response(audio,{headers:{"Content-Type":response.headers.get("content-type")??"audio/wav","Cache-Control":"no-store"}});}catch(error){if((error as Error)?.name==="AbortError")return json({error:"Sahara voice took too long."},504);return json({error:"Dami couldn't reach the voice service."},502);}finally{clearTimeout(timer);}
}
