const { app, BrowserWindow, ipcMain, screen, shell, session, Tray, Menu } = require("electron");
const { spawn } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const WINDOW_WIDTH=280, WINDOW_HEIGHT=330, EDGE_GAP=18;
const DEFAULT_WEB_URL="https://dami-ai-core.vercel.app";
let win=null,tray=null,wakeProcess=null,localSpeechProcess=null,wakeStatus="starting",isQuitting=false;
function settingsPath(){return path.join(app.getPath("userData"),"desktop-settings.json");}
function readSettings(){try{return{dock:"bottom",launchAtStartup:true,wakeWordEnabled:true,webUrl:DEFAULT_WEB_URL,...JSON.parse(fs.readFileSync(settingsPath(),"utf8"))};}catch{return{dock:"bottom",launchAtStartup:true,wakeWordEnabled:true,webUrl:DEFAULT_WEB_URL};}}
function writeSettings(s){fs.writeFileSync(settingsPath(),JSON.stringify(s,null,2),"utf8");}
function dockWindow(position){if(!win)return;const d=screen.getDisplayNearestPoint(screen.getCursorScreenPoint()),{x,y,width,height}=d.workArea;win.setBounds({x:x+width-WINDOW_WIDTH-EDGE_GAP,y:position==="top"?y+EDGE_GAP:y+height-WINDOW_HEIGHT-EDGE_GAP,width:WINDOW_WIDTH,height:WINDOW_HEIGHT},true);}
function syncLoginItem(s){if(process.platform==="win32"||process.platform==="darwin")app.setLoginItemSettings({openAtLogin:s.launchAtStartup!==false});}
function isTrustedAppUrl(raw){try{const u=new URL(raw);if(u.hostname==="localhost"||u.hostname==="127.0.0.1")return true;return u.origin===new URL(readSettings().webUrl||DEFAULT_WEB_URL).origin;}catch{return false;}}
function configurePermissions(){const ses=session.defaultSession;ses.setPermissionCheckHandler((_w,p,o)=>p==="media"&&isTrustedAppUrl(o));ses.setPermissionRequestHandler((w,p,cb,d)=>cb(p==="media"&&isTrustedAppUrl(d?.requestingUrl||w.getURL())));}
function setWakeStatus(s){wakeStatus=s;if(win&&!win.isDestroyed())win.webContents.send("dami:wake-status",s);}
function stopWakeListener(){if(!wakeProcess)return;try{wakeProcess.kill();}catch{}wakeProcess=null;}
function stopLocalSpeech(){if(!localSpeechProcess)return;try{localSpeechProcess.kill();}catch{}localSpeechProcess=null;}
function psRun(script,timeout=15000){return new Promise((resolve,reject)=>{const p=spawn("powershell.exe",["-NoLogo","-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",script],{windowsHide:true});let out="",err="";const timer=setTimeout(()=>{try{p.kill();}catch{}reject(new Error("Local speech timed out"));},timeout);p.stdout.on("data",c=>out+=c.toString());p.stderr.on("data",c=>err+=c.toString());p.on("error",e=>{clearTimeout(timer);reject(e);});p.on("exit",code=>{clearTimeout(timer);if(code===0)resolve(out.trim());else reject(new Error(err.trim()||out.trim()||"Local speech recognition failed"));});});}
async function localSpeak(text){
 if(process.platform!=="win32")throw new Error("Local voice fallback currently requires Windows");
 stopLocalSpeech();
 const safe=Buffer.from(String(text||""),"utf8").toString("base64");
 const script=["$ErrorActionPreference='Stop'","Add-Type -AssemblyName System.Speech","$s=New-Object System.Speech.Synthesis.SpeechSynthesizer","$voices=$s.GetInstalledVoices() | Where-Object {$_.Enabled}","$preferred=$voices | Where-Object {$_.VoiceInfo.Gender -eq 'Female' -and ($_.VoiceInfo.Culture.Name -eq 'en-NG' -or $_.VoiceInfo.Name -match 'Nigeria|African|Yoruba')} | Select-Object -First 1","if(-not $preferred){$preferred=$voices | Where-Object {$_.VoiceInfo.Gender -eq 'Female' -and $_.VoiceInfo.Culture.TwoLetterISOLanguageName -eq 'en'} | Select-Object -First 1}","if($preferred){$s.SelectVoice($preferred.VoiceInfo.Name)}","$s.Rate=0;$s.Volume=100","$t=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('"+safe+"'))","$s.Speak($t)","$s.Dispose()"].join("; ");
 return new Promise((resolve,reject)=>{localSpeechProcess=spawn("powershell.exe",["-NoLogo","-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",script],{windowsHide:true});let err="";localSpeechProcess.stderr.on("data",c=>err+=c.toString());localSpeechProcess.on("error",e=>{localSpeechProcess=null;reject(e);});localSpeechProcess.on("exit",code=>{localSpeechProcess=null;if(code===0)resolve(true);else reject(new Error(err.trim()||"Local voice failed"));});});
}
async function localTranscribe(){
 if(process.platform!=="win32")throw new Error("Local speech fallback currently requires Windows");
 stopWakeListener();setWakeStatus("listening-local");
 const script=["$ErrorActionPreference='Stop'","Add-Type -AssemblyName System.Speech","$installed=[System.Speech.Recognition.SpeechRecognitionEngine]::InstalledRecognizers()","if(-not $installed -or $installed.Count -lt 1){throw 'No Windows speech recognizer is installed'}","$info=$installed | Where-Object {$_.Culture.TwoLetterISOLanguageName -eq 'en'} | Select-Object -First 1","if(-not $info){$info=$installed | Select-Object -First 1}","$r=New-Object System.Speech.Recognition.SpeechRecognitionEngine($info.Id)","$r.LoadGrammar((New-Object System.Speech.Recognition.DictationGrammar))","$r.SetInputToDefaultAudioDevice()","$result=$r.Recognize([TimeSpan]::FromSeconds(15))","if($null -eq $result -or [string]::IsNullOrWhiteSpace($result.Text)){throw 'I did not hear a clear question'}","[Console]::Out.WriteLine('DAMI_TRANSCRIPT:'+$result.Text)","$r.Dispose()"].join("; ");
 try{const out=await psRun(script,19000);const line=out.split(/\r?\n/).find(x=>x.startsWith("DAMI_TRANSCRIPT:"));if(!line)throw new Error("No local transcript was produced");return line.slice(16).trim();}
 finally{if(!isQuitting)setTimeout(()=>startWakeListener(),350);}
}
function startWakeListener(){stopWakeListener();if(process.platform!=="win32"){setWakeStatus("unsupported");return;}if(readSettings().wakeWordEnabled===false){setWakeStatus("disabled");return;}setWakeStatus("starting");const script=["$ErrorActionPreference='Stop'","try {","Add-Type -AssemblyName System.Speech","$installed=[System.Speech.Recognition.SpeechRecognitionEngine]::InstalledRecognizers()","if(-not $installed -or $installed.Count -lt 1){throw 'No Windows speech recognizer is installed'}","$info=$installed | Where-Object {$_.Culture.TwoLetterISOLanguageName -eq 'en'} | Select-Object -First 1","if(-not $info){$info=$installed | Select-Object -First 1}","$r=New-Object System.Speech.Recognition.SpeechRecognitionEngine($info.Id)","$choices=New-Object System.Speech.Recognition.Choices","$choices.Add('hey dami');$choices.Add('hey dummy');$choices.Add('hey demi')","$gb=New-Object System.Speech.Recognition.GrammarBuilder($choices)","$gb.Culture=$info.Culture","$g=New-Object System.Speech.Recognition.Grammar($gb)","$r.LoadGrammar($g)","$r.SetInputToDefaultAudioDevice()","Register-ObjectEvent $r SpeechRecognized -Action {if($Event.SourceEventArgs.Result.Confidence -ge .38){[Console]::Out.WriteLine('DAMI_WAKE');[Console]::Out.Flush()}}|Out-Null","$r.RecognizeAsync([System.Speech.Recognition.RecognizeMode]::Multiple)","[Console]::Out.WriteLine('DAMI_READY');[Console]::Out.Flush()","while($true){Start-Sleep -Milliseconds 500}","} catch {[Console]::Out.WriteLine('DAMI_ERROR:'+$_.Exception.Message);[Console]::Out.Flush();exit 1}"].join("; ");wakeProcess=spawn("powershell.exe",["-NoLogo","-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",script],{windowsHide:true});let b="";wakeProcess.stdout.on("data",c=>{b+=c.toString();const lines=b.split(/\r?\n/);b=lines.pop()||"";for(const raw of lines){const line=raw.trim();if(line==="DAMI_READY")setWakeStatus("ready");else if(line==="DAMI_WAKE"){win?.show();win?.focus();win?.webContents.send("dami:wake-word");}else if(line.startsWith("DAMI_ERROR:")){console.error(line);setWakeStatus("error");}}});wakeProcess.stderr.on("data",c=>console.error("Wake listener stderr",c.toString()));wakeProcess.on("error",e=>{console.error(e);setWakeStatus("error");});wakeProcess.on("exit",code=>{wakeProcess=null;if(!isQuitting&&!String(wakeStatus).startsWith("listening")&&wakeStatus!=="error"&&wakeStatus!=="disabled")setWakeStatus(code===0?"stopped":"error");});}
async function createTray(){if(tray)return;try{tray=new Tray(await app.getFileIcon(process.execPath,{size:"small"}));tray.setToolTip("Dami");tray.setContextMenu(Menu.buildFromTemplate([{label:"Show Dami",click:()=>{win?.show();win?.focus();}},{label:"Hide Dami",click:()=>win?.hide()},{type:"separator"},{label:"Quit Dami",click:()=>{isQuitting=true;app.quit();}}]));tray.on("click",()=>{if(!win)return;if(win.isVisible())win.hide();else{win.show();win.focus();}});}catch(e){console.error("Could not create tray",e);}}
function createWindow(){const s=readSettings();syncLoginItem(s);win=new BrowserWindow({width:WINDOW_WIDTH,height:WINDOW_HEIGHT,minWidth:WINDOW_WIDTH,minHeight:WINDOW_HEIGHT,maxWidth:420,maxHeight:620,frame:false,transparent:true,alwaysOnTop:true,resizable:true,hasShadow:false,show:false,skipTaskbar:true,backgroundColor:"#00000000",webPreferences:{preload:path.join(__dirname,"preload.cjs"),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.setAlwaysOnTop(true,"floating");const base=app.isPackaged?(process.env.DAMI_DESKTOP_URL||s.webUrl||DEFAULT_WEB_URL):(process.env.DAMI_DESKTOP_URL||"http://localhost:3000");void win.loadURL(`${base.replace(/\/$/,"")}/companion?desktop=1`);dockWindow(s.dock);win.webContents.setWindowOpenHandler(({url})=>{if(url.startsWith("https://"))void shell.openExternal(url);return{action:"deny"};});win.webContents.on("will-navigate",(e,url)=>{if(!isTrustedAppUrl(url))e.preventDefault();});win.once("ready-to-show",()=>{win?.show();setWakeStatus(wakeStatus);});win.on("close",e=>{if(!isQuitting){e.preventDefault();win?.hide();}});win.on("closed",()=>win=null);}
app.whenReady().then(async()=>{configurePermissions();ipcMain.handle("dami:get-dock",()=>readSettings().dock);ipcMain.handle("dami:set-dock",(_e,d)=>{if(!["top","bottom"].includes(d))throw new Error("Invalid dock position");writeSettings({...readSettings(),dock:d});dockWindow(d);return d;});ipcMain.handle("dami:set-launch-at-startup",(_e,v)=>{const s={...readSettings(),launchAtStartup:Boolean(v)};writeSettings(s);syncLoginItem(s);return s.launchAtStartup;});ipcMain.handle("dami:get-wake-status",()=>wakeStatus);ipcMain.handle("dami:local-transcribe",()=>localTranscribe());ipcMain.handle("dami:local-speak",(_e,text)=>localSpeak(text));ipcMain.handle("dami:stop-local-speech",()=>{stopLocalSpeech();return true;});ipcMain.handle("dami:show",()=>{win?.show();win?.focus();return true;});ipcMain.handle("dami:hide",()=>{win?.hide();return true;});createWindow();await createTray();startWakeListener();});
app.on("before-quit",()=>{isQuitting=true;stopWakeListener();stopLocalSpeech();});app.on("window-all-closed",()=>{if(process.platform!=="darwin"&&isQuitting)app.quit();});
